browserstack-ie8.json
browserstack.json

This is a work in progress, to debug the issues we're still having with this setup.

Build: Add config for browserstack-runner

---

package.json

This fixes https://github.com/jshint/jshint/issues/2922
Fixes #666

Package.json: bump grunt-contrib-jshint to 0.11.1

---

src/date/parse.js
test/functional/date/parse-date.js
test/unit/date/parse.js
test/util.js

- Handle special case when target date and today date are in different DST rules;
Fixes #689

Date Parser: Improve timezone handling

---

src/date/tokenizer.js
src/number/parse-properties.js
test/functional/date/parse-date.js
test/functional/number/number-parser.js
test/unit.js
test/unit/date/parse.js
test/unit/number/parse-properties.js
test/unit/number/parse.js
test/unit/util/regexp/escape.js

Number: Fix parser to handle empty string

---

src/date/tokenizer.js
test/functional/date/parse-date.js
test/unit.js
test/unit/date/parse.js
test/unit/util/regexp/escape.js

Date: Parse literals, e.g., separators

---

src/date/format-properties.js
src/date/tokenizer-properties.js
test/functional/date/date-formatter.js
test/unit/date/format-properties.js
test/unit/date/parse.js

CLDR introduced additional dayPeriods (e.g., morning1, afternoon1,
evening1, etc) along with am and pm. The new dayPeriods should be handle
by "b" and "B" date patterns, while the "a" pattern should still handle
am/pm.
For Chinese, the corresponding value for either pm or afternoon1 is
exactly the same, therefore it causes problem on the reverse lookup when
parsing.
This change fixes the above parsing issue by filtering am/pm only in the
parser properties. It also filters it out on formatting as a simple
optimization (to avoid unnecessary properties).
Fixes #509
Closes #508

Date: Filter am/pm data for "a" date pattern

---

src/common/runtime-bind.js
src/date-runtime.js
src/date.js
src/date/formatter-fn.js

When dateToPartsFormatter was added, dateFormatter became an alias to
it. Although globalize-compiler can handle it by using
`.compileExtracts()`, it doesn't by using `.compile()` and passing
`formattersAndParsers` argument. This update fixed that.
Amends e4234a7
Ref #678
Ref #697
Ref #700

Date: Fix dateFormatter runtime

---

src/common/validate/skeleton.js
src/common/validate/skeleton/fields-pos-map.js
src/date/expand-pattern.js
test/unit/date/expand-pattern.js

Improve the parameter options.skeleton assertion. Check if passed skeleton is valid by checking the fields range and their order.

Date: Assert options.skeleton

---

src/date/tokenizer-properties.js
src/date/tokenizer.js
test/unit/date/parse.js

parseDate fails on Turkish full datetime with Monday or Saturday.
The root cause is that the parser lookup finds Cuma (Fri) before it
finds Cumartesi (Sat), similarly it finds Pazar (Sun) before it finds
Pazartesi (Mon), and therefore the token doesn't entirely consume the
input.
The fix approach is to start the lookup with longer names, then the
shorter ones.
Fixes #690

Date: Fix parser lookup (use descending order)

---

src/date/tokenizer.js
test/unit/date/parse.js
test/unit/date/tokenizer.js

Date parser: Assert numeric token.value is not NaN

---

package.json
src/date/parse.js

- Include a fix for phantomjs
- Use ZonedDateTime.prototype.toDate()
Fixes #747

Package.json: Bump ZonedDateTime to 1.0.0

---

LICENSE

@scottgonzalez @kborchers please can you confirm this update is ok? Thanks

LICENSE: Add MIT header

---

src/number/pattern-properties.js
test/functional/currency/currency-formatter.js
test/unit/number/pattern-properties.js

This fixes a bug when setting the `minimumFractionDigits` or `maximumFractionDigits` options for number patterns that contain no fraction digits, such as for JPY and other currencies without fraction digits, which currently results in the error E_PAR_OUT_OF_RANGE. The primary use case is for products that don't use fraction digits in their prices for any currency (e.g. $99, £59, 99 €, ￥12,000) and consistently set `maximumFractionDigits: 0`.
Currencies affected: ADP, AFN, ALL, AMD, BIF, BYR, CLP, COP, DJF, ESP, GNF, GYD, IDR, IQD, IRR, ISK, ITL, JPY, KMF, KPW, KRW, LAK, LBP, LUF, MGA, MGF, MMK, MNT, MRO, MUR, PKR, PYG, RSD, RWF, SLL, SOS, STD, SYP, TMM, TRL, TZS, UGX, UZS, UYI, VND, VUV, XAF, XOF, XPF, YER, ZMK, ZWD
Fixes #472
Fixes #565

Number: Fix fraction digit options for patterns with no fraction digits

---

src/date.js

A coworker of mine patched this locally because we were experiencing progressive slow-downs the more we rendered certain pages with lots of dates.
> They are adding and removing an event listener from cldr when we pass in options.timeZone, but since they are constructing the listener with a generator function, they aren't actually removing the one they added. I'll see if I can modify this function and check if that fixes it.
<3z,
Alex

Fix leaking handler in date format setup

---

examples/globalize-compiler/app.js
examples/globalize-compiler/development.html

Examples
Move  Globalize.locale('en') to development.html
Fixes #637

Examples: Make basic globalize-compiler example more generic

---

src/util/number/to-precision.js
test/unit/number/format.js

Fixes: #821 
Removed the logic of rounding the number twice - with a precision of {actual precision required + 2} and then again with the actual precision. This was causing wrong rounding off a number. For eg. 
```
Globalize.numberFormatter({
minimumSignificantDigits: 1,
maximumSignificantDigits: 3,
})(12.849872883)
```
Here the number 12.849872883 is first converted to 12.850 and then when finally rounded off becomes 12.9. But Ideally this should be formatted to 12.8.

Number: Compact formatting with significat digits fix

---

Gruntfile.js
src/date/expand-pattern/augment-format.js
src/date/expand-pattern/get-best-match-pattern.js
test/compiler/cases/date.js
test/functional/date/date-formatter.js
test/functional/date/parse-date.js
test/unit/date/expand-pattern.js
test/unit/date/expand-pattern/augment-format.js
test/unit/date/expand-pattern/get-best-match-pattern.js

Follows this algorithm:
http://www.unicode.org/reports/tr35/tr35-dates.html#Matching_Skeletons
Fixes #753

Date: Add fractional seconds support in formatters

---

src/unit/format.js
test/unit/unit/format.js

When using compound units with the `formatUnit` function, it now correctly displays the formatted value and instead of dumping the raw value into the message.

Unit: Fix formatUnit to display formatted number with compound units

---

src/unit/format.js
test/unit/unit/format.js

Unit: Fix exception using compound units with languages w/o "one" prop

---

src/number/format-properties.js

Adding properties to strings is disallowed in strict mode. Fixes #854

Fix strict mode

---

src/util/number/to-precision.js
test/functional/number/format-number.js

Number:  Added zero check for toPrecision
"formatNumber returns NaN for 0, if max/minimumSignificantDigits is set
Fixed: #706

Number: Added zero check for toPrecision

---

src/util/remove-literal-quotes.js

According to:
> To create a single quote itself, use two in a row: "# o''clock".
https://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Pattern_Character_Definitions

removeLiteralQuotes: Escape '' as a single quote '

---

doc/api/date/date-to-parts-formatter.md

Globalize actually returns lower case `dayperiod`. But the documentation says `dayPeriod`.
This is confusing because `Intl.DateTimeFormat`'s `formatToParts` does return `dayPeriod` but Globalize diverges from this and returns lower case `dayperiod`. This mistake in the documentation can lead to tricky bugs where a developer writes code according to the documentation checking for `dayPeriod` which doesn't work.

Fix dayPeriod and timeZoneName in documentation

---

package.json

Latest version contains multiple fixes and improvements which would be good to have in Globalize :)
Signed-off-by: Georgi Tsaklev <georgi.tsaklev@skyscanner.net>

Bump CLDRjs to 0.5.4

---

.bowerrc
bower.json
package-lock.json
package.json
test/compiler/cases/currency.js
test/compiler/cases/date.js
test/compiler/cases/message.js
test/compiler/cases/number.js
test/compiler/cases/plural.js
test/compiler/cases/relative-time.js
test/compiler/cases/unit.js
test/config.js
test/functional/date/format-date-to-parts.js
test/functional/date/format-date.js
test/functional/date/parse-date.js
test/functional/number/format-number-to-parts.js
test/functional/number/format-number.js
test/unit/date/expand-pattern.js
test/unit/number/format-properties.js
test/unit/number/format.js
test/unit/unit/format.js

Addresses #811 and moves the `cldr-data` package to npm. The latest version of the package is 36 whether the latest version of cldr is 40 now, but i guess it's now closer rather than 25 :D
Anyways I did this one in order to obtain the dayPeriods data which is required to resolve #544.

cldr-data is now loaded from package.json

---

src/build/intro-core-runtime.js
src/build/intro-core.js
src/build/intro-currency-runtime.js
src/build/intro-date-runtime.js
src/build/intro-date.js
src/build/intro-message-runtime.js
src/build/intro-message.js
src/build/intro-number-runtime.js
src/build/intro-number.js
src/build/intro-plural-runtime.js
src/build/intro-plural.js
src/build/intro-relative-time-runtime.js
src/build/intro-relative-time.js
src/build/intro-unit-runtime.js
src/build/intro-unit.js
src/build/intro.min.js

All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/

chore: remove git.io
